### ISSUE TITLE
arewemeetingyet Clock

### ISSUE THREAD

**Issue by AnaFranciscaS** [humanmade/out-of-office#14]
Due to our event having multiple sessions, we're not able to make use of one of Crowdcast's features which enable people to click on the time/date of the event directly in Crowdcast and add it to their calendar. 

Several people have asked about this feature, and because we don't have it, could we instead use the arewemeeting link which shows people what time the event will be in their time zone, please?

**Comment by nomademoiselle** [comment]
Good idea! Here is the link. 
http://arewemeetingyet.com/London/2017-05-30/16:00/Out%20of%20Office%202017
Where should we add it on the website? Could it be in the Header maybe?
Or what about the countdown section?

**Comment by AnaFranciscaS** [comment]
In the header could be good, especially if we can get it added as a link directly underneath the current time and date. It may make the header look a bit too cluttered, but I'd give it a try to see if it works.

**Comment by nomademoiselle** [comment]
@AnaFranciscaS  just updated the link in the header. Let me know if that works!
