### ISSUE TITLE
Website scroll 

### ISSUE THREAD

**Issue by AnaFranciscaS** [humanmade/out-of-office#2]
There seems to be a jumpy scroll when you navigate up and down the site. I can't describe it in any other terms - but if you visit the site and try it, you'll be able to see.

**Comment by nomademoiselle** [comment]
I know it's so annoying! I've asked @joehoyle to look into it in the past and it was a bug in the theme apparently. Didn't seem easy to fix 🙄

**Comment by AnaFranciscaS** [comment]
Oh damn, that's a big shame. It does get very annoying, especially as it sometimes just jumps and skips over huge sections of the site even though your just scrolling.
