### ISSUE TITLE
Add Affiliate Plugin and setup affiliate tracking

### ISSUE THREAD

**Issue by nomademoiselle** [humanmade/out-of-office#4]
https://affiliatewp.com

So we can track the promotional performance of all our partners/speakers and internal promotion.

**Comment by nomademoiselle** [comment]
Just testing the slack integration (sorry)

**Comment by noeltock** [comment]
Are we just looking to track outbound links of partners?

**Comment by nomademoiselle** [comment]
I think it would probably be smart to also track our own links in all our campaigns.

**Comment by nomademoiselle** [comment]
@missjwo I think there was a change to commit code directly to Github instead of being able to make change in Pantheon right? I am not able to add a Plugin anymore as I don't have the FTP credentials.

**Comment by nomademoiselle** [comment]
Installed and setup done!

**Comment by AnaFranciscaS** [comment]
*claps* lovely, thanks!

All affiliate links are being [added here (Affiliate link tab)](https://docs.google.com/spreadsheets/d/1fmzhIhevTXgNOKA5S5MSeiguevSqpj7KYeR38h18_ao/edit#gid=2034636759). We also have a unique link for Human Made, Out of Office and Nomadbase, so we can track our own campaigns, and which I'll be using across social, website and email campaigns.
