### ISSUE TITLE
Fix the section about the past Out of Office event

### ISSUE THREAD

**Issue by nomademoiselle** [humanmade/out-of-office#5]
@AnaFranciscaS do you want me or someone to fix that? It's a pretty nasty clash of color at the moment haha. 
Also do you need me to add the Speaker section and Schedule as well?

<img width="1319" alt="screenshot 2017-04-21 09 49 32" src="https://cloud.githubusercontent.com/assets/14058946/25259446/af3307a2-2678-11e7-82d8-c9075009cd1c.png">

**Comment by AnaFranciscaS** [comment]
Has this been answered for you?

**Comment by nomademoiselle** [comment]
No

**Comment by AnaFranciscaS** [comment]
Cool, yes please fix it. Second part has been answered.

**Comment by nomademoiselle** [comment]
closing
