### ISSUE TITLE
Fix URL

### ISSUE THREAD

**Issue by AnaFranciscaS** [humanmade/out-of-office#7]
Jenny, can we fix this url please? http://www.outofoffice.hm/2016-2/ (so it doesn't have the -2) bear in mind, I've sent it out like this already. So it would be great if the old link was redirected.

**Comment by nomademoiselle** [comment]
@AnaFranciscaS I found out why we couldn't create the url /2016. 

The current URL  http://www.outofoffice.hm/2016/ is the archive link of all blog post written in 2016. So we won't be able to use /2016 for anything else. 

What I suggest is to change the URL http://www.outofoffice.hm/2016-2/ to a keyword instead representing the first edition. It could be something like: http://www.outofoffice.hm/first-edition

Then, I would redirect the link /2016-2/ to this new link, so everywhere you shared it in the past wouldn't become obsolete. 

Let me know what you think.

**Comment by AnaFranciscaS** [comment]
@nomademoiselle thanks for looking into it, what you're suggesting sounds good to me! Go for it.

**Comment by missjwo** [comment]
I was going to suggest : ` edition-1` `edition-2` That way it's easy to  work out what the next one wil be, and it is nto tied to a year - as you might do more than one a year.

Sorry for not getying back to you till now. My original plan was to rewrite the 2016 archive page to be news/2016 but it would be 1000000 times easier to just rename the `2016-2` URL.

**Comment by nomademoiselle** [comment]
Ya I agree with @missjwo for naming it that way. @missjwo do you want to take care of redirecting the link? I'm not sure how to do it since the 2016-2 wouldn't exist anymore?

**Comment by AnaFranciscaS** [comment]
Cool, thank you both - @missjwo edition-1 and edition-2 sounds sensible, and don't worry about doing anything too complicated, I'm happy as long as the URL looks fine and it doesn't make a difference at this stage if it's news/2016. 

Thanks!

**Comment by missjwo** [comment]
In that case- you can change it yourself  and it will keep the  2016-2 rediection. WordPress is smart like that ( thankfully )

**Comment by AnaFranciscaS** [comment]
alright, done!

**Comment by AnaFranciscaS** [comment]
@missjwo I tried to change the slug and it didn't work. Can I hand this back over to you, please?

**Comment by missjwo** [comment]
Fixed and live.
